name: Rust Checks

on:
  push:
    branches:
      - main

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Install ALSA dependencies
              run: sudo apt-get update && sudo apt-get install -y libasound2-dev pkg-config

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
            
            - name: Cargo fmt
              run: cargo fmt --all -- --check

            - name: Cargo clippy
              run: cargo clippy --all-targets --all-features -- -D warnings

            - name: Cargo test
              run: cargo test --all --all-features